version: '3'
networks:
  br_etcd:

services:
  etcd1:
    image: quay.io/coreos/etcd
    container_name: etcd1
    volumes:
      - "./data1:/etcd_data"
    command: 
      - etcd
      - -name
      - etcd1
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://0.0.0.0:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -listen-peer-urls
      - http://0.0.0.0:2380
      # - -initial-cluster-token
      # - etcd-cluster
      - -initial-cluster
      - "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      # - -initial-cluster-state
      # - new
    ports:
      - "23791:2379"
      - "23801:2380"
    networks:
      - br_etcd

  etcd2:
    image: quay.io/coreos/etcd
    container_name: etcd2
    volumes:
      - "./data2:/etcd_data"
    command: 
      - etcd
      - -name
      - etcd2
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://0.0.0.0:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -listen-peer-urls
      - http://0.0.0.0:2380
      # - -initial-cluster-token
      # - etcd-cluster
      - -initial-cluster
      - "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      # - -initial-cluster-state
      # - new
    ports:
      - "23792:2379"
      - "23802:2380"
    networks:
      - br_etcd

  etcd3:
    image: quay.io/coreos/etcd
    container_name: etcd3
    volumes:
      - "./data3:/etcd_data"
    command: 
      - etcd
      - -name
      - etcd3
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://0.0.0.0:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -listen-peer-urls
      - http://0.0.0.0:2380
      # - -initial-cluster-token
      # - etcd-cluster
      - -initial-cluster
      - "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      # - -initial-cluster-state
      # - new
    ports:
      - "23793:2379"
      - "23803:2380"
    networks:
      - br_etcd